### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by menesakdeniz** [komashchenko/LobbySessionFixer#1]
This extension cause server crash, can you fix this?
you can look crashes in this url :
https://crash.limetech.org/stats/5a47496fe5b9fa91fbd5ae413e244f91af6c24e10febd8136223aa15836946a3f632692f

is there any way to debug the extension to locate where it crash?

**Comment by komashchenko** [comment]
This should fix the crash that is happening with you https://github.com/komashchenko/LobbySessionFixer/commit/0abda4da5493e1f67cb97a8d2ff74bf5b5d90a76
